export const PRESENTATION_TOKENS = {
  REGISTER_USE_CASE: Symbol('REGISTER_USE_CASE'),
  LOGIN_USE_CASE: Symbol('LOGIN_USE_CASE'),
  GET_ME_USE_CASE: Symbol('GET_ME_USE_CASE'),
  ASSIGN_ROLE_USE_CASE: Symbol('ASSIGN_ROLE_USE_CASE'),
  REVOKE_ROLE_USE_CASE: Symbol('REVOKE_ROLE_USE_CASE'),
  CREATE_ROLE_USE_CASE: Symbol('CREATE_ROLE_USE_CASE'),
  CREATE_PERMISSION_USE_CASE: Symbol('CREATE_PERMISSION_USE_CASE'),
  LIST_ROLES_USE_CASE: Symbol('LIST_ROLES_USE_CASE'),
  LIST_PERMISSIONS_USE_CASE: Symbol('LIST_PERMISSIONS_USE_CASE'),
};
