import { PRISMA_REPOSITORIES } from './prisma/prisma.constants';

export const IDENTITY_TOKENS = {
  USER_REPOSITORY: PRISMA_REPOSITORIES.USER_REPOSITORY,
  ROLE_REPOSITORY: PRISMA_REPOSITORIES.ROLE_REPOSITORY,
  PERMISSION_REPOSITORY: PRISMA_REPOSITORIES.PERMISSION_REPOSITORY,
  PASSWORD_HASHER: Symbol('IDENTITY_PASSWORD_HASHER'),
  TOKEN_SERVICE: Symbol('IDENTITY_TOKEN_SERVICE'),
} as const;
