export enum TournamentStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  REGISTRATION_OPEN = 'REGISTRATION_OPEN',
  ACTIVE = 'ACTIVE',
  REVIEW = 'REVIEW',
  FINISHED = 'FINISHED',
  ARCHIVED = 'ARCHIVED',
}
