"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "uk" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  uk: {
    "nav.back": "Повернутися",
    "nav.dashboard": "Дашборд",
    "nav.account": "Акаунт",
    "nav.login": "Увійти",
    "nav.register": "Створити профіль",
    "footer.rights": "© 2026 FoldUp. Усі права захищено.",
    "footer.policy": "Політика конфіденційності",
    "footer.terms": "Умови використання",
    "footer.contacts": "Контакти",
    "common.loading": "Завантаження...",
    "common.error": "Помилка",
    "common.save": "Зберегти",
    "common.cancel": "Скасувати",
    "common.send": "Відправити",
    "common.delete": "Видалити",
    "common.nothing_found": "Нічого не знайдено",
    "common.see_more": "Дивитися більше",
    "dashboard.title": "Дашборд",
    "dashboard.back": "Повернутися",
    "dashboard.organizer": "Організатор",
    "dashboard.jury": "Кабінет журі",
    "dashboard.welcome": "Ласкаво просимо",
    "dashboard.tournaments.active": "Твої активні турніри",
    "dashboard.tabs.upcoming": "МАЙБУТНІ ТУРНІРИ",
    "dashboard.tabs.registration": "РЕЄСТРАЦІЯ",
    "dashboard.tabs.current": "ПОТОЧНІ ТУРНІРИ",
    "dashboard.tabs.finished": "ЗАКІНЧЕНІ",
    "dashboard.tournament.status": "Статус",
    "dashboard.tournament.go_to": "Перейти до турніру",
    "dashboard.sidebar.teams": "Мої активні команди",
    "dashboard.sidebar.archive": "Архів турнірів",
    "dashboard.sidebar.logout": "Вийти",
    "dashboard.sidebar.participant": "Учасник",
    "forum.title": "Форум",
    "forum.new_topic": "Нова Гілка",
    "forum.search_placeholder": "Пошук...",
    "forum.subtitle": "Тут ти можеш спілкуватися з іншими користувачами, задавати якісь питання, або комусь допомогти",
    "forum.tags.popular": "Популярні теги",
    "forum.categories.title": "Категорії",
    "consultations.title": "Консультації",
    "consultations.new": "Нова консультація",
    "consultations.subtitle": "Тут ти можеш приєднуватись до запланованих консультацій в рамках Ваших турнірів",
    "consultations.create": "Створити",
    "consultations.none": "У вас ще немає консультацій.",
    "consultations.create_first": "Створіть першу!",
    "consultations.organizer_only": "Тільки організатори можуть створювати консультації.",
    "consultations.status.scheduled": "Заплановано",
    "consultations.status.active": "Йде зараз",
    "consultations.status.ended": "Завершено",
    "consultations.status.cancelled": "Скасовано",
    "dashboard.organizer.title": "Кабінет організатора",
    "dashboard.organizer.subtitle": "Керуйте своїми турнірами та публікуйте нові",
    "dashboard.organizer.create": "Створити турнір",
    "dashboard.organizer.stats.total": "Всього турнірів",
    "dashboard.organizer.stats.drafts": "Чернетки",
    "dashboard.organizer.stats.active": "Активні",
    "dashboard.organizer.stats.finished": "Завершено",
    "dashboard.organizer.none": "У вас ще немає турнірів",
    "dashboard.organizer.create_first": "Створити перший турнір",
    "dashboard.organizer.publish": "Опублікувати",
    "dashboard.organizer.published": "Опубліковано!",
    "dashboard.organizer.view": "Переглянути",
    "dashboard.jury.title": "Кабінет журі",
    "dashboard.jury.subtitle": "Тут ви можете переглядати подані роботи та виставляти оцінки",
    "dashboard.jury.stats.total": "Всього робіт",
    "dashboard.jury.stats.pending": "Очікують оцінки",
    "dashboard.jury.stats.reviewed": "Оцінено",
    "dashboard.jury.none": "Немає поданих робіт для перевірки",
    "dashboard.jury.pending_title": "Очікують оцінки",
    "dashboard.jury.reviewed_title": "Оцінені роботи",
    "dashboard.jury.score": "Оцінити",
    "dashboard.jury.edit": "Редагувати",
    "dashboard.jury.hide": "Сховати",
    "dashboard.jury.save_score": "Зберегти оцінку",
    "tournament.back": "Повернутися",
    "tournament.team_tournament": "Командний турнір",
    "tournament.main_info": "Головна інформація",
    "tournament.reg_end": "Кінець реєстрації",
    "tournament.start": "Початок турніру",
    "tournament.end": "Кінець турніру",
    "tournament.timeline": "Timeline",
    "tournament.rounds": "Раунди турніру",
    "tournament.reg_prompt": "Для реєстрації на командний турнір",
    "tournament.join": "Приєднатися до турніру",
    "tournament.to_dashboard": "До дошки",
    "tournament.status.draft": "Чернетка",
    "tournament.status.registration": "Реєстрація відкрита",
    "tournament.status.active": "Триває",
    "tournament.status.finished": "Завершено",
    "tournament.registration_closed": "Реєстрація закрита",
    "tournament.tournament_finished": "Турнір завершено",
    "jury.back": "Повернутися",
    "jury.main": "Головна",
    "jury.leaderboard": "Лідерборд",
    "jury.submissions": "Список робіт для оцінювання",
    "jury.evaluation_criteria": "Критерії оцінювання:",
    "jury.technical_part": "I. Технічна частина",
    "jury.functionality": "II. Функціональність",
    "jury.comment": "Коментар",
    "jury.comment_placeholder": "Залишити коментар...",
    "jury.save_score": "Зберегти оцінку",
    "jury.update_score": "Оновити оцінку",
    "jury.score_saved": "Оцінку збережено",
    "jury.eco.timeline": "Timeline турніру",
    "jury.eco.reg_end_msg": "Кінець реєстрації — ",
    "jury.eco.start_msg": "Початок турніру — ",
    "jury.eco.end_msg": "Завершення турніру — ",
    "jury.eco.no_rounds": "Раунди не додані",
    "jury.eco.tech_backend": "Backend якість коду (clean code, патерни, ООП, відсутність помилок, тести)",
    "jury.eco.tech_db": "Database (наявність/налаштування, структура)",
    "jury.eco.tech_frontend": "Frontend (clean code, патерни, відсутність помилок, UX/UI, тести)",
    "jury.eco.func_req": "Виконання вимог завдання (\"must have\")",
    "jury.eco.func_bugs": "Роботоздатність, відсутність багів",
    "jury.eco.func_ux": "Зручність використання",
    "jury.eco.rounds_count": "Кількість раундів",
    "jury.eco.until": "до",
    "jury.eco.no_desc": "Опис відсутній",
    "jury.eco.tournament": "Турнір",
    "jury.eval.not_found": "Роботу не знайдено",
    "jury.eval.crit1": "Критерій 1",
    "jury.eval.crit2": "Критерій 2",
    "jury.eval.crit3": "Критерій 3",
    "jury.eval.total": "Загальна сума балів",
    "jury.eval.description": "Опис",
    "jury.eval.video": "Відео презентація",
    "jury.eval.no_video": "Відео не завантажено",
    "jury.eval.github": "Посилання на GitHub",
    "jury.eval.live_demo": "Live Demo",
    "jury.eval.comments": "Коментарі",
    "jury.eval.min_score_err": "Введіть оцінку більше 0",
    "jury.subs.title": "Загальний список команд",
    "jury.subs.empty": "Робіт для оцінювання ще немає",
    "jury.lb.error": "Помилка завантаження лідерборду",
    "jury.lb.empty": "Поки що немає оцінених робіт",
    "jury.lb.team": "Команда",
    "landing.hero.title": "FOLDUP",
    "landing.hero.subtitle": "Об'єднуємо інтелект, будуємо майбутнє разом.",
    "landing.hero.btn": "Знайти турнір",
    "landing.features.intro1": "FoldUp — це інноваційна платформа для командних змагань, де навчання перетворюється на захопливий квест.",
    "landing.features.intro2": "Ми стираємо кордони між теорією та практикою, допомагаючи кожному знайти своє місце в цифровій спільноті однодумців.",
    "landing.features.img_alt": "Команда презентує ідеї",
    "landing.audience.title": "Для кого цей застосунок?",
    "landing.audience.img_alt": "Спільна командна робота",
    "landing.audience.intro": "Ми створили простір, де цифровізація служить людям, а не навпаки. Наша платформа — це міст між поколіннями та ролями:",
    "landing.audience.students.title": "Для учнів та студентів:",
    "landing.audience.students.desc": "Можливість прокачати «soft skills», навчитися працювати в команді та розв'язувати реальні кейси у форматі гри. Це не просто навчання — це пошук друзів та професійне зростання незалежно від віку.",
    "landing.audience.mentors.title": "Для вчителів та менторів:",
    "landing.audience.mentors.desc": "Зручний інструмент для організації турнірів, автоматизації оцінювання та відстеження прогресу. Ми даємо можливість навчати цікаво, використовуючи сучасний UX/UI підхід.",
    "landing.audience.peers.title": "Для однодумців:",
    "landing.audience.peers.desc": "Завдяки цифровим інструментам ви миттєво знаходите партнерів для проєктів, обмінюєтеся досвідом та створюєте спільні продукти.",
    "landing.achievements.title": "Наші досягнення та шлях",
    "landing.achievements.img1_alt": "Команда на зустрічі",
    "landing.achievements.img2_alt": "Учасники освітнього заходу",
    "landing.achievements.intro": "Ми трансформуємо процес навчання, перетворюючи його на результативну командну гру:",
    "landing.achievements.efficiency.title": "Ефективність:",
    "landing.achievements.efficiency.desc": "Завдяки цифровізації ми об'єднуємо сотні однодумців, забезпечуючи прозоре оцінювання та високу залученість учасників.",
    "landing.achievements.tech.title": "Технологічність:",
    "landing.achievements.tech.desc": "Платформа побудована на сучасній архітектурі, що гарантує стабільність під час пікових навантажень та зручність у роботі з дедлайнами.",
    "landing.achievements.future.title": "Майбутнє:",
    "landing.achievements.future.desc": "Ми масштабуємо систему, впроваджуючи нові інструменти для аналітики успішності та ще тіснішої взаємодії між командами.",
    "landing.achievements.img3_alt": "Команда в офісі",
    "landing.cta.title": "Зацікавило?",
    "landing.cta.subtitle": "Знаходь однодумців та команду",
    "landing.cta.find_btn": "Знайти турнір",
    "landing.cta.reg_btn": "Зареєструватися",
    "landing.contacts.title": "Контактна інформація",
    "landing.contacts.subtitle": "Зв'яжіться з адміністрацією, якщо виникнуть питання:",
    "common.deadline": "Дедлайн",
    "common.unknown": "Невідомий",
    "forum.empty_topics": "Ще немає гілок. Будьте першим!",
    "forum.tags_placeholder": "Теги з'являться після створення гілок",
    "forum.pagination_shown": "Показано {shown} із {total} гілок",
    "time.min_ago": "{n} хв. тому",
    "time.h_ago": "{n} год. тому",
    "time.d_ago": "{n} дн. тому",
  },
  en: {
    "nav.back": "Back",
    "nav.dashboard": "Dashboard",
    "nav.account": "Account",
    "nav.login": "Log In",
    "nav.register": "Create Profile",
    "footer.rights": "© 2026 FoldUp. All rights reserved.",
    "footer.policy": "Privacy Policy",
    "footer.terms": "Terms of Use",
    "footer.contacts": "Contacts",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.send": "Send",
    "common.delete": "Delete",
    "common.nothing_found": "Nothing found",
    "common.see_more": "See more",
    "dashboard.title": "Dashboard",
    "dashboard.back": "Back",
    "dashboard.organizer": "Organizer",
    "dashboard.jury": "Jury Cabinet",
    "dashboard.welcome": "Welcome",
    "dashboard.tournaments.active": "Your active tournaments",
    "dashboard.tabs.upcoming": "UPCOMING TOURNAMENTS",
    "dashboard.tabs.registration": "REGISTRATION",
    "dashboard.tabs.current": "CURRENT TOURNAMENTS",
    "dashboard.tabs.finished": "FINISHED",
    "dashboard.tournament.status": "Status",
    "dashboard.tournament.go_to": "Go to tournament",
    "dashboard.sidebar.teams": "My active teams",
    "dashboard.sidebar.archive": "Tournaments Archive",
    "dashboard.sidebar.logout": "Logout",
    "dashboard.sidebar.participant": "Participant",
    "forum.title": "Forum",
    "forum.new_topic": "New Topic",
    "forum.search_placeholder": "Search...",
    "forum.subtitle": "Here you can communicate with other users, ask questions, or help someone",
    "forum.tags.popular": "Popular tags",
    "forum.categories.title": "Categories",
    "consultations.title": "Consultations",
    "consultations.new": "New Consultation",
    "consultations.subtitle": "Here you can join scheduled consultations within your tournaments",
    "consultations.create": "Create",
    "consultations.none": "You have no consultations yet.",
    "consultations.create_first": "Create the first one!",
    "consultations.organizer_only": "Only organizers can create consultations.",
    "consultations.status.scheduled": "Scheduled",
    "consultations.status.active": "Active",
    "consultations.status.ended": "Ended",
    "consultations.status.cancelled": "Cancelled",
    "dashboard.organizer.title": "Organizer Cabinet",
    "dashboard.organizer.subtitle": "Manage your tournaments and publish new ones",
    "dashboard.organizer.create": "Create Tournament",
    "dashboard.organizer.stats.total": "Total Tournaments",
    "dashboard.organizer.stats.drafts": "Drafts",
    "dashboard.organizer.stats.active": "Active",
    "dashboard.organizer.stats.finished": "Finished",
    "dashboard.organizer.none": "You have no tournaments yet",
    "dashboard.organizer.create_first": "Create your first tournament",
    "dashboard.organizer.publish": "Publish",
    "dashboard.organizer.published": "Published!",
    "dashboard.organizer.view": "View",
    "dashboard.jury.title": "Jury Cabinet",
    "dashboard.jury.subtitle": "Here you can view submitted works and set scores",
    "dashboard.jury.stats.total": "Total Works",
    "dashboard.jury.stats.pending": "Pending Evaluation",
    "dashboard.jury.stats.reviewed": "Reviewed",
    "dashboard.jury.none": "No submitted works for review",
    "dashboard.jury.pending_title": "Pending Evaluation",
    "dashboard.jury.reviewed_title": "Reviewed Works",
    "dashboard.jury.score": "Score",
    "dashboard.jury.edit": "Edit",
    "dashboard.jury.hide": "Hide",
    "dashboard.jury.save_score": "Save Score",
    "tournament.back": "Back",
    "tournament.team_tournament": "Team Tournament",
    "tournament.main_info": "Main Information",
    "tournament.reg_end": "Registration Deadline",
    "tournament.start": "Tournament Start",
    "tournament.end": "Tournament End",
    "tournament.timeline": "Timeline",
    "tournament.rounds": "Tournament Rounds",
    "tournament.reg_prompt": "To register for the team tournament",
    "tournament.join": "Join Tournament",
    "tournament.to_dashboard": "To Dashboard",
    "tournament.status.draft": "Draft",
    "tournament.status.registration": "Registration Open",
    "tournament.status.active": "Active",
    "tournament.status.finished": "Finished",
    "tournament.registration_closed": "Registration closed",
    "tournament.tournament_finished": "Tournament finished",
    "jury.back": "Back",
    "jury.main": "Main",
    "jury.leaderboard": "Leaderboard",
    "jury.submissions": "List of works for evaluation",
    "jury.evaluation_criteria": "Evaluation Criteria:",
    "jury.technical_part": "I. Technical Part",
    "jury.functionality": "II. Functionality",
    "jury.comment": "Comment",
    "jury.comment_placeholder": "Leave a comment...",
    "jury.save_score": "Save Score",
    "jury.update_score": "Update Score",
    "jury.score_saved": "Score Saved",
    "jury.eco.timeline": "Tournament Timeline",
    "jury.eco.reg_end_msg": "Registration Deadline — ",
    "jury.eco.start_msg": "Tournament Start — ",
    "jury.eco.end_msg": "Tournament End — ",
    "jury.eco.no_rounds": "No rounds added",
    "jury.eco.tech_backend": "Backend code quality (clean code, patterns, OOP, no errors, tests)",
    "jury.eco.tech_db": "Database (presence/configuration, structure)",
    "jury.eco.tech_frontend": "Frontend (clean code, patterns, no errors, UX/UI, tests)",
    "jury.eco.func_req": "Fulfillment of task requirements (\"must have\")",
    "jury.eco.func_bugs": "Reliability, absence of bugs",
    "jury.eco.func_ux": "Ease of use",
    "jury.eco.rounds_count": "Number of rounds",
    "jury.eco.until": "until",
    "jury.eco.no_desc": "No description",
    "jury.eco.tournament": "Tournament",
    "jury.eval.not_found": "Work not found",
    "jury.eval.crit1": "Criterion 1",
    "jury.eval.crit2": "Criterion 2",
    "jury.eval.crit3": "Criterion 3",
    "jury.eval.total": "Total Score",
    "jury.eval.description": "Description",
    "jury.eval.video": "Video Presentation",
    "jury.eval.no_video": "No video uploaded",
    "jury.eval.github": "GitHub Link",
    "jury.eval.live_demo": "Live Demo",
    "jury.eval.comments": "Comments",
    "jury.eval.min_score_err": "Enter a score greater than 0",
    "jury.subs.title": "General list of teams",
    "jury.subs.empty": "No works for evaluation yet",
    "jury.lb.error": "Error loading leaderboard",
    "jury.lb.empty": "No reviewed works yet",
    "jury.lb.team": "Team",
    "landing.hero.title": "FOLDUP",
    "landing.hero.subtitle": "Bringing minds together, building the future as one.",
    "landing.hero.btn": "Find a tournament",
    "landing.features.intro1": "FoldUp is an innovative platform for team competitions where learning becomes a captivating quest.",
    "landing.features.intro2": "We blur the line between theory and practice, helping every participant find a place in a digital community of like-minded people.",
    "landing.features.img_alt": "Team presenting ideas",
    "landing.audience.title": "Who is this app for?",
    "landing.audience.img_alt": "Team collaboration",
    "landing.audience.intro": "We built a space where digitalization serves people, not the other way around. Our platform bridges generations and roles:",
    "landing.audience.students.title": "For students:",
    "landing.audience.students.desc": "A chance to level up soft skills, learn teamwork and solve real cases through gameplay. Not just learning — it's finding friends and growing professionally regardless of age.",
    "landing.audience.mentors.title": "For teachers and mentors:",
    "landing.audience.mentors.desc": "A convenient tool to organize tournaments, automate scoring and track progress. Teach engagingly with a modern UX/UI approach.",
    "landing.audience.peers.title": "For peers:",
    "landing.audience.peers.desc": "Digital tools let you instantly find project partners, share experience and create products together.",
    "landing.achievements.title": "Our milestones and path",
    "landing.achievements.img1_alt": "Team meeting",
    "landing.achievements.img2_alt": "Education event participants",
    "landing.achievements.intro": "We transform learning into an effective team game:",
    "landing.achievements.efficiency.title": "Efficiency:",
    "landing.achievements.efficiency.desc": "Digitalization unites hundreds of minds, with transparent scoring and high engagement.",
    "landing.achievements.tech.title": "Tech:",
    "landing.achievements.tech.desc": "Built on modern architecture for stability under peak loads and effortless deadline tracking.",
    "landing.achievements.future.title": "Future:",
    "landing.achievements.future.desc": "We're scaling the system with new analytics and even tighter team collaboration tools.",
    "landing.achievements.img3_alt": "Team in office",
    "landing.cta.title": "Interested?",
    "landing.cta.subtitle": "Find like-minded people and a team",
    "landing.cta.find_btn": "Find a tournament",
    "landing.cta.reg_btn": "Sign up",
    "landing.contacts.title": "Contact information",
    "landing.contacts.subtitle": "Reach out to the administration if you have questions:",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("uk");

  useEffect(() => {
    const savedLang = localStorage.getItem("lang") as Language;
    if (savedLang && (savedLang === "uk" || savedLang === "en")) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("lang", lang);
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
